regions:
- global
- ap-southeast-1
- ap-southeast-2
- ap-south-1
- ap-northeast-1
- ap-northeast-2
- ap-northeast-3
- ca-central-1
- cn-north-1
- cn-northwest-1
- sa-east-1
- eu-west-1
- eu-west-2
- eu-west-3
- eu-central-1
- eu-north-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2


account-blacklist:
    - "211147541504"

accounts:
    654608353261:
        filters:
          IAMRole:
          - "yudho-workshop2"
          IAMRolePolicyAttachment:
          - "admin -> AdministratorAccess"
          IAMPolicy:
          - "AdministratorAccess"
    
  
